Models/Product.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace ClothingStore.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey("Category")]
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Please enter a product name")]
        public string Name { get; set; }
        
        public string ImageUrl { get; set; }
        
        public bool IsFavorite { get; set; }
        
        [Required(ErrorMessage = "Please enter product's price")]
        [Range(0.01, double.MaxValue,ErrorMessage = "Please enter a positive price")]
        public decimal Price { get; set; } = 0;
        
        [Range(0, int.MaxValue, ErrorMessage = "Please enter a positive number or null")]
        public int Available { get; set; } = 0; //наличие товара
        
        public string Description { get; set; }

        [BindNever]
        public bool IsSlide { get; set; }

        public Category Category { get; set; }        
    }
}

Controllers/AdminController.cs
namespace ClothingStore.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public AdminController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _productRepository.GetAllProductsAsync();
            foreach (var product in products)
            {
                var category = await _categoryRepository.GetCategoryAsync(product.CategoryId);
                product.Category = category;
            }
            return View(products);
        }

        [HttpGet]
        public IActionResult CreateProduct() => PartialView();
        

        [HttpPost]
        public async Task<IActionResult> CreateProduct(Product product)
        {
            if (ModelState.IsValid)
            {
                product.ImageUrl = @$"/img/download/{product.ImageUrl}";
                product.Category = await _categoryRepository.GetCategoryByNameAsync(product.Category.Name);
                await _productRepository.CreateProductAsync(product);
                TempData["message"] = $"{product.Name} has been created";
                return RedirectToAction("Index");
            }
            return View(product);
        }

        [HttpGet]
        public async Task<IActionResult> EditProduct(int productId)
        {
            var product = await _productRepository.GetProductAsync(productId);
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> EditProduct(Product product)
        {
            if(ModelState.IsValid)
            {
                product.ImageUrl = @$"/img/download/{product.ImageUrl}";
                await _productRepository.UpdateProductAsync(product);
                TempData["message"] = $"{product.Name} has been saved";
                return RedirectToAction("Index");
            }
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProduct(int productId)
        {
            var deletedProduct = await _productRepository.GetProductAsync(productId);
            await _productRepository.DeleteProductAsync(deletedProduct.Id);
            if(deletedProduct != null)
            {                
                TempData["message"] = $"{deletedProduct.Name} was deleted";
            }            
            return RedirectToAction("Index");
        }
    }
}

Controllers/CategoryController.cs
namespace ClothingStore.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        
        public int PageSize = 4;
                       
        public CategoryController(IProductRepository productRepository, 
            ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;            
            _categoryRepository = categoryRepository;           
        }
        
        public async Task<IActionResult> ProductList(string category, int page = 1)
        {
            Category currentCategory = await _categoryRepository
                    .GetCategoryByNameAsync(category);
            List<Product> products = await _productRepository
                    .GetProductsOnPageAsync(currentCategory, page, PageSize); ;

            var model = new ProductListViewModel
            {
                ProductsByCategory = products,
                CurrentCategory = currentCategory,
                PageInfo = new PageInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _productRepository.GetProductsByCategoryAsync(currentCategory)
                                                   .Result.Count
                }
            };                                                       
            return View(model);            
        }        
    }
}

Controllers/OrderController.cs
namespace ClothingStore.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShopCart _shopCart;
        public OrderController(IOrderRepository orderRepository, ShopCart shopCart)
        {
            _orderRepository = orderRepository;
            _shopCart = shopCart;
        }

        [Authorize]
        public async Task<IActionResult> OrderList()
        {
            var orders = await _orderRepository.Orders.Where(о => !о.Shipped).ToListAsync();
            return View(orders);
        }
            
        [HttpPost]
        [Authorize]
        public IActionResult MarkShipped(int orderId)
        {
            Order order = _orderRepository.Orders.FirstOrDefault(o => o.Id == orderId);

            if (order != null)
            {
                order.Shipped = true;
                _orderRepository.SaveAsync();                                    
            }
            return RedirectToAction("OrderList");
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            if (_shopCart.ShopCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Shop cart is empty");
                return RedirectToAction("Error");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {

            if (ModelState.IsValid)
            {
                order.Items = _shopCart.ShopCartItems;
                await _orderRepository.CreateOrderAsync(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }

        public IActionResult Complete()
        {
            _shopCart.Clear();
            ViewBag.Message = "Order is complete";
            return View();
        }

        public IActionResult Error()
        {
            ViewBag.Message = "Shopping cart is empty";
            return View();
        }
    }
}

Views/Shared/ProductForm.cshtml
@model Product

<div class="form-group">
    <div class="col-md-2">
        <h6 style="font-weight:normal;">Category</h6>
        <select asp-for="Category.Name" class="form-select" aria-label="Default select example">
            <option value="Man Store">Man's</option>
            <option value="Woman Store">Woman's'</option>
            <option value="Shoes">Shoes</option>
            <option value="Accesories">Accesories</option>
            <option value="Sale">Sale</option>
            <option value="Vintage">Vintage</option>
        </select>
    </div>
</div>
<div class="form-group">
    <label asp-for="Name"></label>
    <div class="col-md-2">
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
</div>
<div class="form-group">
    <label asp-for="Price"></label>
    <div class="col-md-1">
        <input asp-for="Price" class="form-control" rows="2" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
</div>
<div class="form-group mt-2 mb-2">
    <label asp-for="ImageUrl"></label>
    <div class="col-md-1">
        <input type="file" asp-for="ImageUrl" class="" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
</div>
<div class="form-group">
    <label asp-for="Description"></label>
    <div class="col-md-3">
        <textarea asp-for="Description" class="form-control" rows="3"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
</div>
<div class="form-group">
    <label asp-for="Available"></label>
    <div class="col-md-1">
        <input asp-for="Available" class="form-control" />
        <span asp-validation-for="Available" class="text-danger"></span>
    </div>
</div>
<div class="form-group mt-2 mb-3">
    <input type="checkbox" class="form-check-input" asp-for="IsFavorite">
    <label class="form-check-label" asp-for="IsFavorite">Add to favorites</label>
    <span asp-validation-for="IsFavorite" class="text-danger"></span>
</div>

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" runat="server" type="image/x-icon" />
    <link href="~/favicon.ico" rel="icon" runat="server" type="image/ico" />

    <link rel="stylesheet" type="text/css" href="~/lib/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/slick/slick-theme.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/all.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/style.min.css" />

    <!--Validation style-->
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
</head>
<body>        
    <div class="row featured-products-section pb-2">
        <div class="col offset-1"> 
            <h3>@ViewBag.Title</h3>
        </div>
        <div class="col-3">
            <a class="link-admin" asp-action="OrderList" asp-controller="Order">Order Management</a>
            <a class="link-admin" asp-action="Index" asp-controller="Home">Home</a>
            <a class="link-admin" asp-action="Logout" asp-controller="Account">Log Out</a>            
        </div>
    </div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    
    @RenderBody()    
    
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/lib/slick/slick.min.js"></script>
    <script src="~/js/main.js"></script>

</body>
</html>

Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/style.min.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Clothing Store</title>
    <link href="~/favicon.ico" rel="shortcut icon" runat="server" type="image/x-icon" />
    <link href="~/favicon.ico" rel="icon" runat="server" type="image/ico" />

    <link rel="stylesheet" type="text/css" href="~/lib/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/slick/slick-theme.css" />    
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/all.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/style.min.css" />

    <!--Validation style-->
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <a asp-controller="Home" asp-action="Index"><img src="~/img/Aditii.png" alt="Logo" /></a>
                </div>
                <div class="col-lg-6 offset-lg-1">
                    @await Component.InvokeAsync("SearchPanel")
                </div>
                <div class="col-lg-2 offset-lg-1">
                    @await Component.InvokeAsync("CartTotalPrice")
                </div>
            </div>
        </div>
    </header>

    <div class="navbar">
        <div class="container">
            <ul>
                <li>
                    <a class="nav-section" asp-controller="Home" asp-action="Index">HOME</a>
                    <span class="delimiter">|</span>
                </li>
                <li>
                    <a class="nav-section" asp-controller="Category" asp-action="ProductList" asp-route-category="Woman Store">WOMAN STORE</a>
                    <span class="delimiter">|</span>
                </li>
                <li>
                    <a class="nav-section" asp-controller="Category" asp-action="ProductList" asp-route-category="Accesories">ACCESSORIES</a>
                    <span class="delimiter">|</span>
                </li>
                <li>
                    <a class="nav-section" asp-controller="Category" asp-action="ProductList" asp-route-category="Man Store">MAN STORE</a>
                    <span class="delimiter">|</span>
                </li>
                <li>
                    <a class="nav-section" asp-controller="Category" asp-action="ProductList" asp-route-category="Shoes">SHOES</a>
                    <span class="delimiter">|</span>
                </li>
                <li>
                    <a class="nav-section" asp-controller="Category" asp-action="ProductList" asp-route-category="Sale">SALE</a>
                    <span class="delimiter">|</span>
                </li>
                <li>
                    <a class="nav-section" asp-controller="Category" asp-action="ProductList" asp-route-category="Vintage">VINTAGE</a>
                    <span class="delimiter">|</span>
                </li>

                <li>
                    <a class="nav-section" asp-controller="Admin" asp-action="Index">PROFILE</a>
                    <span class="delimiter">|</span>
                </li>
                <li>
                    <a class="nav-section" href="#services">SERVICES</a>
                    <span class="delimiter">|</span>
                </li>
                <li><a class="nav-section" asp-controller="Home" asp-action="ContactUs">CONTACT US</a></li>
            </ul>
        </div>
    </div>

    @RenderBody()

    <footer>
        <p class="copyright">Copyright © 2022 DarBerg</p>
    </footer>

    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/lib/slick/slick.min.js"></script>
    <script src="~/js/main.js"></script>

</body>
</html>