Models/Category.cs
namespace ClothingStore.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        
        public string Name { get; set; }
              
        public string Description { get; set; }
        public List<Product> Products { get; set; }
    }
}

ViewModels/ProductListViewModel.cs
namespace ClothingStore.ViewModels
{
    public class ProductListViewModel
    {
        public Category CurrentCategory { get; set; }
        public List<Product> ProductsByCategory { get; set; }
        public PageInfo PageInfo { get; set; }
    }
}

Controllers/CategoryController.cs
namespace ClothingStore.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        
        public int PageSize = 4;
                       
        public CategoryController(IProductRepository productRepository, 
            ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;            
            _categoryRepository = categoryRepository;           
        }
        
        public async Task<IActionResult> ProductList(string category, int page = 1)
        {
            Category currentCategory = await _categoryRepository
                    .GetCategoryByNameAsync(category);
            List<Product> products = await _productRepository
                    .GetProductsOnPageAsync(currentCategory, page, PageSize); ;

            var model = new ProductListViewModel
            {
                ProductsByCategory = products,
                CurrentCategory = currentCategory,
                PageInfo = new PageInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _productRepository.GetProductsByCategoryAsync(currentCategory)
                                                   .Result.Count
                }
            };                                                       
            return View(model);            
        }        
    }
}

Controllers/ShopCartController.cs
namespace ClothingStore.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ShopCart _shopCart;

        public ShopCartController(IProductRepository productRepository, ShopCart shopCart)
        {
            _productRepository = productRepository;
            _shopCart = shopCart;
        }   


        public IActionResult Cart()
        {            
            var cart = new ShopCartViewModel
            {
                ShopCart = _shopCart
            };            
            return View(cart);
        }

        public async Task<RedirectToActionResult> AddToCart(int id)
        {
            var item = await _productRepository.GetProductAsync(id);
            if (item != null)                            
                _shopCart.AddItem(item, 1);                
            
            return RedirectToAction("Cart");
        }

        public RedirectToActionResult DeleteFromCart(int id)
        {            
            _shopCart.DeleteItem(id);                       
            return RedirectToAction("Cart");
        }        
    }
}

Views/Category/ProductList.cshtml
@model ProductListViewModel

<div class="container">
    <h1>@Model.CurrentCategory.Name</h1>    
    <div class="row">
        @{
            foreach (var product in Model.ProductsByCategory)
            {
                <div class="col-lg-3 featured-product">
                    <img class="featured-img" src="@product.ImageUrl" alt="@product.Name">
                    <h4 class="featured-title">@product.Name</h4>
                    <p class="featured-price">$@product.Price</p>
                    <button class="featured-btn">
                        <a class="featured-product-link" asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@product.Id">
                            BUY NOW
                        </a>
                    </button>
                </div>              
            }           
        }
    </div>
    <div class="row mt-4">
        <div page-model="@Model.PageInfo" page-action="ProductList" page-classes-enabled="true"
            page-class="btn" page-class-normal="btn-secondary" style="width:12px;"
            page-class-selected="pagination-btn-success" style="width:12px;" class="btn-group pull-right offset-lg-5 col-lg-1"
            page-url-category="@Model.CurrentCategory.Name">
        </div>
    </div>
</div>